version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: card_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: card_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - card_network

volumes:
  mysql_data:

networks:
  card_network:
    driver: bridge